config/routes.rb
Rails.application.routes.draw do

  root :to => 'messages#index'

  resources :messages
  resources :doctor_messages
  resources :prescriptions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :inbox
  belongs_to :outbox

  validates :body, presence: true
  validates :body, length: { maximum: 500 }

  scope :unread, -> { where(read: false) }

  def sent_more_than_a_week_ago?
    created_at < DateTime.current.ago(7.days)
  end

  def sent_less_than_a_week_ago?
    !sent_more_than_a_week_ago?
  end

  self.per_page = 10

end

app/models/outbox.rb
class Outbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.patient_initial_message
    current.inbox.messages.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordInvalid, with: :record_invalid_response

  def record_invalid_response
    redirect_to '/', status: :bad_request
  end

  protected
  def current_user
    raise 'redefine me in a child class'
  end
end

app/controllers/doctor_messages_controller.rb
class DoctorMessagesController < ApplicationController
  def index
    messages = User.default_doctor.inbox.messages.paginate(page: params[:page])
    render :index, locals: { messages: messages, current_user: current_user }
  end

  def show
    message = Message.find(params[:id])
    MarkMessageRead.new(message).execute
    render :show, locals: { message: message }
  end

  protected

  def current_user
    User.default_doctor
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    messages = User.current.inbox.messages.paginate(page: params[:page])
    render :index, locals: { messages: messages, current_user: current_user }
  end
  def show
    message = Message.find(params[:id])
    render :show, locals: { message: message }
  end

  def new
    @message = Message.new
  end

  def create
    User.current.outbox.messages.create!(permitted_params)

    redirect_to '/', status: 200
  rescue NoMethodError => e
    logger.error('Failed to send message')
    logger.error(e.message)
    redirect_to '/', status: 500
  end

  protected
  def current_user
    User.current
  end

  private

  def permitted_params
    {
      body: params[:message].permit(:body)[:body],
      read: false,
      inbox_id: recipient.inbox.id
    }
  end

  def recipient
    User.patient_initial_message.sent_less_than_a_week_ago? ? User.default_doctor : User.default_admin
  end

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController

  REISSUE_PRESCRIPTION_TEXT = 'Hello, esteemed sir. I lost my prescription and would like to kindly ask you to issue a new one. Sincerely'

  def create
    ActiveRecord::Base.transaction do
      Message.create!(
        outbox_id: current_user.outbox.id,
        inbox_id: User.default_admin.inbox.id,
        body: REISSUE_PRESCRIPTION_TEXT
      )
      CreatePayment.new(current_user).execute
    end

    PaymentProviderFactory.provider.debit_card(current_user)
    redirect_to '/', status: 200
  end

  protected
  def current_user
    User.current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_messages_helper.rb
module DoctorMessagesHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/doctor_messages/index.html.erb
<%= render partial: 'shared/messages', locals: { messages: messages, current_user: current_user } %>

app/views/doctor_messages/show.html.erb
<%= render partial: 'shared/message', locals: { message: message } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuaMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/index.html.erb
<%= render partial: 'shared/messages', locals: { messages: messages, current_user: current_user } %>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>

  <div class="card-body">
    <%= form_for @message do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/show.html.erb
<%= render partial: 'shared/message', locals: { message: message } %>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox
        <% end  %>
      </li>
      <li class="nav-item active">
        <%= link_to doctor_messages_path, class: 'nav-link' do %>
          Doctor Inbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_message.html.erb
<% label = "I've lost my script, please issue a new one at a charge of €10" %>

<div class="card my-3 ">
  <h5 class="card-header">
    <% if message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= message.outbox.user.full_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= message.body %></p>
    <% if message.inbox.user.is_patient? %>
      <%= link_to "Reply", new_message_path, class: "btn btn-primary" %>
      <%= link_to label, prescriptions_path, { method: :post, class: "btn btn-primary" } %>
    <% end %>
  </div>
</div>

app/views/shared/_messages.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Inbox</h6>
  <% if current_user.is_doctor? %>
    <h6 class="pb-2 mb-0">Total Unread Messages: <%= current_user.inbox.messages.unread.count %> </h6>
  <% end %>

  <% messages.each do |message| %>
    <%
      message_link = current_user.is_patient? ? message_path(message) : doctor_message_path(message)
      content = message.body.truncate(45)
    %>
    <%= link_to message_link do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.read ? content : raw("<b>#{content}</b>") %>
        </p>
      </div>
    <% end %>
  <% end %>

  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>

  <div class="digg_pagination">
    <%= will_paginate messages, container: false %>
  </div>
</div>